---

- block:
    - name: Compile inside a container with buildah
      command: >
        buildah bud -v '{{ local_source_directory }}/fuse-overlayfs:/build/fuse-overlayfs'
        -t fuse-overlayfs -f ./Containerfile.static.ubuntu .
      args:
        chdir: '{{ local_source_directory }}/fuse-overlayfs'

    - name: Copy fuse-overlayfs from source
      copy:
        src: '{{ local_source_directory }}/fuse-overlayfs/fuse-overlayfs'
        dest: /usr/bin/fuse-overlayfs
        mode: '755'
        remote_src: yes
  become: '{{ do_become }}'
  tags: [fuse-overlayfs, packages]
